apriltag:                 # node name
  ros__parameters:
    
    image_transport: raw  # image format: "raw" or "compressed"
    family: 36h11         # tag family name: 16h5, 25h9, 36h11
    size: 0.2          # default tag edge size in meter
    profile: false        # print profiling information to stdout

    # tuning of detection (defaults)
    max_hamming: 0        # maximum allowed hamming distance (corrected bits)
    detector:
      threads: 1          # number of threads
      decimate: 2.0       # decimate resolution for quad detection
      blur: 0.0           # sigma of Gaussian blur for quad detection
      refine: true           # snap to strong gradients
      sharpening: 0.25    # sharpening of decoded images
      debug: false            # write additional debugging images to current working directory
    
    pose_estimation_method: "pnp" # method for estimating the tag pose

    tag:
      # Lista dos IDs das tags que você está a usar
      ids:    [241, 242, 243, 244]
      frames: ["tag241", "tag242", "tag243", "tag244"]


